### ISSUE TITLE
Speicherzugriffsfehler with latest deb

### ISSUE THREAD

**Issue by JanHBade** [john30/ebusd#436] opened 2021-05-26 10:33 UTC
Hello,

when starting ebusd getting "Speicherzugriffsfehler" with the actual src it works.

(on a Rasperry Pi Zero)

**Comment by john30** [comment] 2021-06-06 16:27
duplicate of #394, see https://github.com/john30/ebusd-debian/issues/5

**Closed as completed by john30** 2021-06-06 16:27 UTC
Labels: duplicate
