### ISSUE TITLE
Unable to load from NVS

### ISSUE THREAD

**Issue by M4271** [john30/ebusd#1341] opened 2024-09-22 16:57 UTC
### Description

The first time I used the ebusd adapter I was able to use the easi interface and connect to my wifi.

Now, the second time (some weeks later) I am not able to connect anymore. When I use the easi interface for most of the commands I receive the following:

```
easi> sta
error: unable to load from NVS
Command returned non-zero error code: 0x1 (ERROR)
```

I did flash the latest FW 2024-08-25 but it did not fix this issue.

Anyone knows what could cause this issue? Might this be a HW defect?

### Actual behavior

NVS is working

### Expected behavior

NVS is not available

### ebusd version

other

### ebusd arguments

NA

### Operating system

other

### CPU architecture

x64

### Dockerized

None

### Hardware interface

Adapter Shield v5 via USB

### Related integration

other

### Logs

NA

**Comment by john30** [comment] 2024-09-22 17:41
not an ebusd issue and duplicate of https://github.com/john30/ebusd-esp32/issues/71

**Closed as not planned by john30** 2024-09-22 17:41 UTC
Labels: invalid
