### ISSUE TITLE
ebusd service does not start after firmware update

### ISSUE THREAD

**Issue by Norb1204** [john30/ebusd#1383] opened 2024-11-08 15:31 UTC
### Description

After firmware update to version 2024-10-27, ebusd service do not start.
<img width="614" alt="image" src="https://github.com/user-attachments/assets/a42f0d38-43f7-4816-b279-62597b48fbbf">

When I go back to the previous firmware (version 2024-01-06), the same problem occurs, the ebusd service does not start anymore.
I still have an old V3 adapter with this adapter everything works fine.

Maybe the adapter v5 is broken now?

see also:
https://github.com/john30/ebusd-esp32/issues/67

### ebusd version
24.1

### ebusd arguments

EBUSD_OPTS="--scanconfig=full --configpath=/etc/ebusd/ -d ens:/dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_DC:54:75:63:64:C4-if00 -p 8888 -l /var/log/ebusd.log --loglevel=error --logareas=network  --httpport=8889 --htmlpath=/var/ebusd/html --accesslevel=install --updatecheck=off"

### Operating system
Debian 12 (Bookworm)

### CPU architecture
x64

### Hardware interface
Adapter Shield v5 via USB

**Comment by Norb1204** [comment] 2024-11-08 16:13
I still have an old ebus 3 adapter, this still works.
The Shield v5 adapter may have a problem after I tried to download the latest software version (2024-10-27). Going back to the old software (version 2024-01-06) is now the same problem.
Maybe the adapter is broken now?

**Comment by Norb1204** [comment] 2024-11-09 15:49
I am one step closer to finding the error:
If I delete the characters of the USB path after ...DC:54, I can start the ebusd service.

**ebus service starts:**
EBUSD_OPTS="--scanconfig=full --configpath=/etc/ebusd/ -d ens:/dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_DC:54<s>:75:63:64:C4-if00</s> -p 8888 -l /var/log/ebusd.log --loglevel=error --logareas=network --httpport=8889 --htmlpath=/var/ebusd/html --accesslevel=install --updatecheck=off"

**ebus service cannot be started:**
EBUSD_OPTS="--scanconfig=full --configpath=/etc/ebusd/ -d ens:/dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_DC:54:75:63:64:C4-if00  -p 8888 -l /var/log/ebusd.log --loglevel=error --logareas=network --httpport=8889 --htmlpath=/var/ebusd/html --accesslevel=install --updatecheck=off"

I think the problem has something to do with the various updates of the PI 5. Please have a look at the ebusd Software application, maybe there is a bug.

**Comment by john30** [comment] 2024-11-11 06:35
duplicate of #1374

**Closed as not planned by john30** 2024-11-11 06:35 UTC
Labels: duplicate
