### ISSUE TITLE
also Problems with Kernel 4.19.42-v7+

### ISSUE THREAD

**Issue by SailingTom** [john30/ebusd#285] opened 2019-06-10 07:35 UTC
Hi John,

i am also having Problems since i have updated my Raspi 3 to Kernel 4.19.42-v7+
The ebus ( with rpi-adapter from reinhart ) starts as normal, but aquires no signal.

#EBUSD_OPTS="--scanconfig -d /dev/ttyebus -c http://ebusd.eu/config/ -l var/log/ebusd.log"

Any Options ??

Best Wishes

Tom

**Comment by john30** [comment] 2019-06-10 08:17
duplicate of #283

**Closed as completed by john30** 2019-06-10 08:17 UTC
Labels: duplicate
