### ISSUE TITLE
1-wire Sensor connected to ebus adapter is not included in the MQTT

### ISSUE THREAD

**Issue by mintgroen** [john30/ebusd#1393] opened 2024-11-22 11:21 UTC
### Description

I have connected a 1-wire DS18B20 to pin D7, 3.3v and gnd and the value shows in the status column:

![Screenshot from 2024-11-22 12-15-15](https://github.com/user-attachments/assets/66d91dce-3da3-4768-a152-e36eaa880d2d)

Enabled MQTT server:

![Screenshot from 2024-11-22 12-15-59](https://github.com/user-attachments/assets/7a35b155-2a90-4d55-b698-caba46089b68)

MQTT reports connected:

![Screenshot from 2024-11-22 12-16-37](https://github.com/user-attachments/assets/12083707-dda1-4af7-adb6-4316770b429b)

### Actual behavior

![Screenshot from 2024-11-22 12-17-32](https://github.com/user-attachments/assets/37f8c9de-f2db-41c7-b963-61a0921e79f8)

Defined topic pops up in the MQTT server with some info but the sensor value is not included

### Expected behavior

Sensor value transmitted to MQTT  server

### ebusd version

24.1

### ebusd arguments

None

### Operating system

Debian 10 (Buster) / Ubuntu 18-19 / Raspbian 10 / Raspberry Pi OS 10 (including lite)

### CPU architecture

arm64

### Dockerized

None

### Hardware interface

Adapter Shield v5 via WiFi

### Logs

Cant find any related log info in that file.

**Comment by djungelorm** [comment] 2024-11-22 19:51
I am also seeing this behaviour on the C6. +1 to get this feature added.

The sensor values do show up on the HTTP API though, via: `http://<ip-address>/api/v1/pin`

**Comment by john30** [comment] 2024-11-24 06:26
not an ebusd issue, so closing here.
use https://github.com/john30/ebusd-esp32 instead.
anyway, duplicate of https://github.com/john30/ebusd-esp32/issues/68

**Closed as not planned by john30** 2024-11-24 06:26 UTC
Labels: invalid

**Comment by mintgroen** [comment] 2024-11-25 18:18
> I am also seeing this behaviour on the C6. +1 to get this feature added.
> 
> The sensor values do show up on the HTTP API though, via: `http://<ip-address>/api/v1/pin`

Ok, easy to fix that in Node red and relay the info to MQTT.
