### ISSUE TITLE
Move away from csv to xml or json or yaml

### ISSUE THREAD

**Issue by thomaskilian** [john30/ebusd#1308] opened 2024-07-12 21:36 UTC
### Description

The current csv structure represents a 3-dimensional structure flattened into s 2-dimensional one. It would be more easily to understand, maintain and extend if this structure would be described in something more appropriate. It's not overly complex, so xml might be overkil. json would well cover the needs, but yaml would also be ok. While json is more machine-oriented, yaml can more easily be edited by humans. Also for a migration it would probably be not too difficult to offer a tool to migrate existing csv into the new format. And having the possibility to have both side by side should also not be a difficulty.

**Comment by john30** [comment] 2024-07-13 04:00
closed as duplicate of #30

**Closed as not planned by john30** 2024-07-13 04:00 UTC
Labels: duplicate, invalid
