### ISSUE TITLE
Improve poll priority handling

### ISSUE THREAD

**Issue by MarkusGH** [john30/ebusd#1036] opened 2023-10-10 17:37 UTC
### Description

Currently messages with lower poll priority are sent in blocks.

This leads to the unwanted (at least by me) behaviour that messages with lower poll priority can still significantly delay messages with higher poll priority.

Example:

r1 A
r5 B
r5 C
r5 D
r5 E
r5 F

Currently this will be sent like:

AAAAABCDEF AAAAABCDEF etc.
So the interval between the A messages (with poll priority 1) is 11116 111116 poll cycles (min 1, max 6, average 2 cycles).
The delay between the BCDEF messages (with poll priority 5) is always 10 cycles as expected (5 times longer).

A IMHO better sequence would be:

ABACADAEAF ABACADAEAF etc.

For that reason I suggest to pick the next poll message in a round-robin like fashion.

**Comment by john30** [comment] 2023-10-14 15:04
duplicate of #129

**Closed as not planned by john30** 2023-10-14 15:04 UTC
Labels: duplicate
