### ISSUE TITLE
no reliable scanning result / no reliable data for Vaillant VRC700 (ERR: wrong symbol received)

### ISSUE THREAD

**Issue by bertvandevoorde** [john30/ebusd#757] opened 2022-12-11 14:09 UTC
### Description

I've been struggling for two days to get reliable data on the ebus of my Vaillant Ecotec system. In any case I have to make sure that my ebus usb coupler device is running before I start the heating system. If I don't do this, then it won't detect all of the devices during the scan. It will even take half an our or so before it detects the thermostat VRC700. It will then show up as detected in "ebusctl info" but it will not load the 15.700.csv configuration file.

My Vaillant system has 4 components:
Vaillant Ecotec boiler Ecotec plus (addr 8) , two Thermostats VRC700  (addr 15) and VR91 (addr 35)  + central pump steering VR70 (addr 52).

I use the following foreground command to run ebusd: ebusd -f -d /dev/ttyUSB0 --scanconfig=15 -c /etc/ebusd/ --mqtthost=192.168.1.100 --mqttport=1883 --mqttuser=user --mqttpass=pass --pollinterval=180 --latency=20000 --acquiretimeout=15000
--> notice how I don't specify --scanconfig=full but rather focus on the address of the VRC700.
I have a feeling that I don't have a lot of margin here, the slightest difference in any of the parameters and this impacts scanning behaviour and would make it so that certain csv files are not loaded. With the exact configuration above, I reach a point where my infrastructure is detected and it would load at least 3 csv files. See below:

address 03: master https://github.com/john30/ebusd/issues/11
address 08: slave https://github.com/john30/ebusd/issues/11, scanned "MF=Vaillant;ID=BAI00;SW=0105;HW=7803", loaded "vaillant/bai.308523.inc", "vaillant/08.bai.csv"
address 10: master https://github.com/john30/ebusd/issues/2
address 15: slave https://github.com/john30/ebusd/issues/2, scanned "MF=Vaillant;ID=70000;SW=0614;HW=6903", loaded "vaillant/15.700.csv"
address 30: master https://github.com/john30/ebusd/issues/3
address 31: master https://github.com/john30/ebusd/issues/8, ebusd
address 35: slave https://github.com/john30/ebusd/issues/3, scanned "MF=Vaillant;ID=VR_91;SW=0415;HW=4803"
address 36: slave https://github.com/john30/ebusd/issues/8, ebusd
address 52: slave, scanned "MF=Vaillant;ID=VR_70;SW=0109;HW=2903", loaded "vaillant/52.vr_70.csv"

I'm able to read a couple of simple counters like "outsidetemp" and I have data for the boiler (BAI00) like the water temperature. I also have all of this in my MQTT broker. The thing is that anything coming from the VRC700 (15.700.csv) remains unreadable on the bus. "find -v" will show "no data stored" for all of the parameters. If I try to read something: "read Hc1PumpStatus" then I get "ERR: wrong symbol received" every time. It's like the system doesn't know how to make sense from what is coming in from the VRC700.

The logging shows resolved data for all the components but then regularly throws messages like this
2022-12-10 14:47:35.357 [update notice] received unknown MS cmd: 3015b5240a06010a01070000007842 / 02000a
I guess these come from the VRC700

Actually I feel like something is acting very sensitive. The "ERR: wrong symbol received" error troubles me a lot and it is also this error which is very often thrown if I start the USB coupler while the heating system is already running. I then receive this error for all addresses and the ebus service never reaches a point where scanning finishes. Even if scanning does finish for one device, it would never load the csv.

### Actual behavior

The erratic "(ERR: wrong symbol received)" on the ebus impacts scanning and reliable loading the csv files (I think) and definitely impacts reading the data from the VRC700.  I have been playing around a lot with the potentiometer a lot and I'm suspecting it is fine now since I can actually get data from the BAI and the VR70 component. 

### Expected behavior

I'm expecting that everything will work satisfactory if I can get rid of the "ERR: wrong symbol received" problem on the bus.

### ebusd version

22.4

### ebusd arguments

-d /dev/ttyUSB0 --scanconfig=15 -c /etc/ebusd/ --mqtthost=192.168.1.100 --mqttport=1883 --mqttuser=user --mqttpass=pass --pollinterval=180 --latency=20000 --acquiretimeout=15000

### Operating system

Debian 9 (Stretch) / Ubuntu 16-17 / Raspbian 9 / Raspberry Pi OS 9 (including lite)

### CPU architecture

armv7l

### Dockerized

None

### Hardware interface

Esera USB

### Related integration

TCP (cmdline client like ebusctl or netcat)

### Logs

/var/log/ebusd.log during normal operation (only address 8 resolved correctly)

2022-12-11 14:50:31.135 [update notice] received unknown MS cmd: 1052b523080100ff0000ffff00 / 0101
2022-12-11 14:50:31.383 [update notice] received unknown MS cmd: 1052b5230402010000 / 02019c
2022-12-11 14:50:40.036 [update notice] received read bai Status01 QQ=10: 29.0;29.0;2.750;-;50.0;off
2022-12-11 14:50:40.172 [main error] scan config 35: ERR: ACK error
2022-12-11 14:50:40.333 [update notice] received unknown MS cmd: 1052b5230103 / 0f008000800080008084016901c87d00
2022-12-11 14:50:40.602 [update notice] received update-write bai SetMode QQ=10: auto;0.0;-;-;1;0;0;0;0;0
2022-12-11 14:50:41.167 [update notice] received unknown MS cmd: 1052b523080100ff0000ffff00 / 0101
2022-12-11 14:50:41.416 [update notice] received unknown MS cmd: 1052b5230402010000 / 02019c
2022-12-11 14:50:42.292 [main error] scan config 52: ERR: wrong symbol received
2022-12-11 14:50:50.076 [update notice] received read bai Status01 QQ=10: 29.0;29.0;2.750;-;50.0;off
2022-12-11 14:50:50.370 [update notice] received unknown MS cmd: 1052b5230103 / 0f008000800080008084016901c87d00
2022-12-11 14:50:50.643 [update notice] received update-write bai SetMode QQ=10: auto;0.0;-;-;1;0;0;0;0;0
2022-12-11 14:50:50.905 [update notice] received read bai Status02 QQ=10: auto;60;75.0;70;70.0
2022-12-11 14:50:51.207 [update notice] received unknown MS cmd: 1052b523080100ff0000ffff00 / 0101
2022-12-11 14:50:51.457 [update notice] received unknown MS cmd: 1052b5230402010000 / 02019c

debugging using command
ebusd --scanconfig=full -c /etc/ebusd/ --enablehex --lograwdata --logareas=all --logfile=/var/log/ebusd.log --loglevel debug -f

2022-12-11 15:16:51.741 [main notice] ebusd 22.4.v22.4 started with full scan on device /dev/ttyUSB0
2022-12-11 15:16:51.741 [main info] loading configuration files from /etc/ebusd/
2022-12-11 15:16:51.741 [main debug] reading directory /etc/ebusd/
2022-12-11 15:16:51.742 [main debug] file type of /etc/ebusd/broadcast.csv is file
2022-12-11 15:16:51.742 [main debug] file type of /etc/ebusd/mqtt-hassio.cfg is file
2022-12-11 15:16:51.742 [main debug] file type of /etc/ebusd/memory.csv is file
2022-12-11 15:16:51.742 [main debug] file type of /etc/ebusd/mqtt-integration.cfg is file
2022-12-11 15:16:51.742 [main debug] file type of /etc/ebusd/vaillant is dir
2022-12-11 15:16:51.742 [main debug] file type of /etc/ebusd/_templates.csv is file
2022-12-11 15:16:51.742 [main debug] file type of /etc/ebusd/knx.cfg is file
2022-12-11 15:16:51.742 [main info] reading templates /
2022-12-11 15:16:51.748 [main info] read templates in /
2022-12-11 15:16:51.748 [main info] reading file broadcast.csv
2022-12-11 15:16:51.752 [main info] successfully read file broadcast.csv
2022-12-11 15:16:51.752 [main info] reading file memory.csv
2022-12-11 15:16:51.755 [main info] successfully read file memory.csv
2022-12-11 15:16:51.755 [main info] read config files, got 11 messages
2022-12-11 15:16:51.778 [bus notice] bus started with own address 31/36
2022-12-11 15:16:51.779 [main info] registering data handlers
2022-12-11 15:16:51.779 [main info] registered data handlers
2022-12-11 15:16:51.803 [bus debug] ERR: SYN received during no signal, switching to ready
2022-12-11 15:16:51.803 [bus notice] signal acquired
2022-12-11 15:16:56.330 [bus notice] new master 10, master count 2
2022-12-11 15:16:56.396 [bus notice] new master 03, master count 3
2022-12-11 15:16:56.396 [update info] received MS cmd: 1008b5110101 / 094635c002ff630100ff
2022-12-11 15:16:56.397 [update notice] received unknown MS cmd: 1008b5110101 / 094635c002ff630100ff
2022-12-11 15:16:56.401 [bus notice] <1008b51101018900094635c002ff630100ff2600
2022-12-11 15:16:56.691 [update info] received MS cmd: 1052b5230103 / 0f008000800080008036022702c87d00
2022-12-11 15:16:56.691 [update notice] received unknown MS cmd: 1052b5230103 / 0f008000800080008036022702c87d00
2022-12-11 15:16:56.695 [bus notice] <1052b523010376000f008000800080008036022702c87d002f00
2022-12-11 15:16:56.965 [update info] received MS cmd: 1008b51009000046ffffff000000 / 0101
2022-12-11 15:16:56.965 [update notice] received unknown MS cmd: 1008b51009000046ffffff000000 / 0101
2022-12-11 15:16:56.969 [bus notice] <1008b51009000046ffffff0000006b0001019a00
2022-12-11 15:16:57.224 [update info] received MS cmd: 1008b5110102 / 06033c96468c64
2022-12-11 15:16:57.225 [update notice] received unknown MS cmd: 1008b5110102 / 06033c96468c64
2022-12-11 15:16:57.229 [bus notice] <1008b51101028a0006033c96468c64e900
2022-12-11 15:16:57.530 [update info] received MS cmd: 1052b523080100ff0000ffff00 / 0101
2022-12-11 15:16:57.530 [update notice] received unknown MS cmd: 1052b523080100ff0000ffff00 / 0101
2022-12-11 15:16:57.534 [bus notice] <1052b523080100ff0000ffff00780001019a00
2022-12-11 15:16:57.776 [update info] received MS cmd: 1052b5230402010145 / 020100
2022-12-11 15:16:57.776 [update notice] received unknown MS cmd: 1052b5230402010145 / 020100
2022-12-11 15:16:57.780 [bus notice] <1052b5230402010145c700020100b700
2022-12-11 15:17:01.780 [main debug] performing regular tasks
2022-12-11 15:17:01.780 [main notice] starting initial full scan
2022-12-11 15:17:01.780 [bus info] scan 02 cmd: 3102070400
2022-12-11 15:17:01.796 [bus debug] start request 31
2022-12-11 15:17:01.796 [bus debug] arbitration start with 31
2022-12-11 15:17:01.845 [bus debug] arbitration won
2022-12-11 15:17:01.845 [bus debug] arbitration delay 453 micros
2022-12-11 15:17:01.845 [bus info] arbitration delay 453 - 453 micros
2022-12-11 15:17:01.845 [bus debug] switching from ready to send command
2022-12-11 15:17:01.852 [bus debug] send/receive symbol latency 6 ms
2022-12-11 15:17:01.852 [bus info] send/receive symbol latency 6 - 6 ms
2022-12-11 15:17:01.860 [bus debug] send/receive symbol latency 6 ms
2022-12-11 15:17:01.867 [bus debug] send/receive symbol latency 6 ms
2022-12-11 15:17:01.874 [bus debug] send/receive symbol latency 6 ms
2022-12-11 15:17:01.874 [bus debug] switching from send command to send command CRC
2022-12-11 15:17:01.881 [bus debug] send/receive symbol latency 6 ms
2022-12-11 15:17:01.881 [bus debug] switching from send command CRC to receive command ACK
2022-12-11 15:17:01.885 [bus debug] notify request: ERR: ACK error
2022-12-11 15:17:01.885 [bus info] scan 04 cmd: 3104070400
2022-12-11 15:17:01.885 [bus debug] ERR: ACK error during receive command ACK, switching to skip
2022-12-11 15:17:01.886 [bus debug] start request 31
2022-12-11 15:17:01.886 [bus debug] arbitration start with 31
2022-12-11 15:17:01.928 [bus notice] >310207040030<d5
2022-12-11 15:17:01.934 [bus debug] arbitration won
2022-12-11 15:17:01.934 [bus debug] arbitration delay 448 micros
2022-12-11 15:17:01.934 [bus info] arbitration delay 448 - 453 micros
2022-12-11 15:17:01.934 [bus debug] switching from ready to send command
2022-12-11 15:17:01.941 [bus debug] send/receive symbol latency 6 ms
2022-12-11 15:17:01.948 [bus debug] send/receive symbol latency 6 ms
2022-12-11 15:17:01.955 [bus debug] send/receive symbol latency 6 ms
2022-12-11 15:17:01.962 [bus debug] send/receive symbol latency 6 ms
2022-12-11 15:17:01.962 [bus debug] switching from send command to send command CRC
2022-12-11 15:17:01.969 [bus debug] notify request: ERR: wrong symbol received
2022-12-11 15:17:01.970 [bus info] scan 05 cmd: 3105070400
2022-12-11 15:17:01.970 [bus debug] ERR: wrong symbol received during send command CRC, switching to skip
2022-12-11 15:17:01.970 [bus debug] start request 31
2022-12-11 15:17:01.970 [bus debug] arbitration start with 31
2022-12-11 15:17:02.015 [bus notice] >31040704006f<4ffd
2022-12-11 15:17:02.021 [bus debug] arbitration won
2022-12-11 15:17:02.021 [bus debug] arbitration delay 460 micros
2022-12-11 15:17:02.021 [bus info] arbitration delay 448 - 460 micros
2022-12-11 15:17:02.021 [bus debug] switching from ready to send command
2022-12-11 15:17:02.028 [bus debug] send/receive symbol latency 6 ms
2022-12-11 15:17:02.035 [bus debug] send/receive symbol latency 6 ms
2022-12-11 15:17:02.042 [bus debug] send/receive symbol latency 6 ms
2022-12-11 15:17:02.049 [bus debug] send/receive symbol latency 6 ms
2022-12-11 15:17:02.049 [bus debug] switching from send command to send command CRC
2022-12-11 15:17:02.056 [bus debug] notify request: ERR: wrong symbol received
2022-12-11 15:17:02.056 [bus info] scan 06 cmd: 3106070400
2022-12-11 15:17:02.056 [bus debug] ERR: wrong symbol received during send command CRC, switching to skip
2022-12-11 15:17:02.057 [bus debug] start request 31
2022-12-11 15:17:02.057 [bus debug] arbitration start with 31
2022-12-11 15:17:02.103 [bus notice] >310507040031<01fd
2022-12-11 15:17:02.108 [bus debug] arbitration won
2022-12-11 15:17:02.108 [bus debug] arbitration delay 459 micros
2022-12-11 15:17:02.108 [bus debug] switching from ready to send command
2022-12-11 15:17:02.115 [bus debug] send/receive symbol latency 6 ms
2022-12-11 15:17:02.122 [bus debug] send/receive symbol latency 6 ms
2022-12-11 15:17:02.129 [bus debug] send/receive symbol latency 6 ms
2022-12-11 15:17:02.136 [bus debug] send/receive symbol latency 6 ms
2022-12-11 15:17:02.136 [bus debug] switching from send command to send command CRC
2022-12-11 15:17:02.143 [bus debug] notify request: ERR: wrong symbol received
2022-12-11 15:17:02.143 [bus info] scan 08 cmd: 3108070400
2022-12-11 15:17:02.143 [bus debug] ERR: wrong symbol received during send command CRC, switching to skip
2022-12-11 15:17:02.144 [bus debug] start request 31
2022-12-11 15:17:02.144 [bus debug] arbitration start with 31
2022-12-11 15:17:02.190 [bus notice] >3106070400d3<53f5
2022-12-11 15:17:02.195 [bus debug] arbitration won
2022-12-11 15:17:02.196 [bus debug] arbitration delay 442 micros
2022-12-11 15:17:02.196 [bus info] arbitration delay 442 - 460 micros
2022-12-11 15:17:02.196 [bus debug] switching from ready to send command
2022-12-11 15:17:02.203 [bus debug] send/receive symbol latency 6 ms
2022-12-11 15:17:02.210 [bus debug] send/receive symbol latency 5 ms
2022-12-11 15:17:02.210 [bus info] send/receive symbol latency 5 - 6 ms
2022-12-11 15:17:02.217 [bus debug] send/receive symbol latency 5 ms
2022-12-11 15:17:02.224 [bus debug] send/receive symbol latency 5 ms
2022-12-11 15:17:02.224 [bus debug] switching from send command to send command CRC
2022-12-11 15:17:02.231 [bus debug] notify request: ERR: wrong symbol received
2022-12-11 15:17:02.231 [bus info] scan 09 cmd: 3109070400
2022-12-11 15:17:02.231 [bus debug] ERR: wrong symbol received during send command CRC, switching to skip
2022-12-11 15:17:02.232 [bus debug] start request 31
2022-12-11 15:17:02.232 [bus debug] arbitration start with 31
2022-12-11 15:17:02.277 [bus notice] >3108070400d1<81fd
2022-12-11 15:17:02.282 [bus debug] arbitration won
2022-12-11 15:17:02.283 [bus debug] arbitration delay 627 micros
2022-12-11 15:17:02.283 [bus info] arbitration delay 442 - 627 micros
2022-12-11 15:17:02.283 [bus debug] switching from ready to send command
2022-12-11 15:17:02.290 [bus debug] send/receive symbol latency 5 ms
2022-12-11 15:17:02.297 [bus debug] send/receive symbol latency 5 ms
2022-12-11 15:17:02.304 [bus debug] send/receive symbol latency 5 ms
2022-12-11 15:17:02.311 [bus debug] send/receive symbol latency 5 ms
2022-12-11 15:17:02.311 [bus debug] switching from send command to send command CRC
2022-12-11 15:17:02.318 [bus debug] notify request: ERR: wrong symbol received
2022-12-11 15:17:02.318 [bus info] scan 0a cmd: 310a070400
2022-12-11 15:17:02.318 [bus debug] ERR: wrong symbol received during send command CRC, switching to skip
2022-12-11 15:17:02.319 [bus debug] start request 31
2022-12-11 15:17:02.319 [bus debug] arbitration start with 31
2022-12-11 15:17:02.365 [bus notice] >31090704008f<0ff5
2022-12-11 15:17:02.371 [bus debug] arbitration won
2022-12-11 15:17:02.371 [bus debug] arbitration delay 446 micros
2022-12-11 15:17:02.371 [bus debug] switching from ready to send command
2022-12-11 15:17:02.378 [bus debug] send/receive symbol latency 5 ms
2022-12-11 15:17:02.385 [bus debug] send/receive symbol latency 5 ms
2022-12-11 15:17:02.392 [bus debug] send/receive symbol latency 5 ms
2022-12-11 15:17:02.399 [bus debug] send/receive symbol latency 5 ms
2022-12-11 15:17:02.399 [bus debug] switching from send command to send command CRC
2022-12-11 15:17:02.406 [bus debug] notify request: ERR: wrong symbol received
2022-12-11 15:17:02.406 [bus info] scan 0b cmd: 310b070400
2022-12-11 15:17:02.406 [bus debug] ERR: wrong symbol received during send command CRC, switching to skip
2022-12-11 15:17:02.407 [bus debug] start request 31
2022-12-11 15:17:02.407 [bus debug] arbitration start with 31
2022-12-11 15:17:02.452 [bus notice] >310a0704006d<0df5
2022-12-11 15:17:02.457 [bus debug] arbitration won
2022-12-11 15:17:02.457 [bus debug] arbitration delay 412 micros
2022-12-11 15:17:02.458 [bus info] arbitration delay 412 - 627 micros
2022-12-11 15:17:02.458 [bus debug] switching from ready to send command
2022-12-11 15:17:02.465 [bus debug] send/receive symbol latency 5 ms
2022-12-11 15:17:02.472 [bus debug] send/receive symbol latency 5 ms
2022-12-11 15:17:02.479 [bus debug] send/receive symbol latency 5 ms
2022-12-11 15:17:02.486 [bus debug] send/receive symbol latency 5 ms
2022-12-11 15:17:02.486 [bus debug] switching from send command to send command CRC
2022-12-11 15:17:02.493 [bus debug] notify request: ERR: wrong symbol received
2022-12-11 15:17:02.493 [bus info] scan 0c cmd: 310c070400
2022-12-11 15:17:02.494 [bus debug] ERR: wrong symbol received during send command CRC, switching to skip
2022-12-11 15:17:02.494 [bus debug] start request 31
2022-12-11 15:17:02.494 [bus debug] arbitration start with 31
2022-12-11 15:17:02.538 [bus notice] >310b07040033<23fc
2022-12-11 15:17:02.543 [bus debug] arbitration won
2022-12-11 15:17:02.543 [bus debug] arbitration delay 607 micros
2022-12-11 15:17:02.544 [bus debug] switching from ready to send command
2022-12-11 15:17:02.550 [bus debug] send/receive symbol latency 5 ms
2022-12-11 15:17:02.557 [bus debug] send/receive symbol latency 5 ms
2022-12-11 15:17:02.564 [bus debug] send/receive symbol latency 5 ms
2022-12-11 15:17:02.571 [bus debug] send/receive symbol latency 5 ms
2022-12-11 15:17:02.571 [bus debug] switching from send command to send command CRC
2022-12-11 15:17:02.578 [bus debug] send/receive symbol latency 6 ms
2022-12-11 15:17:02.578 [bus debug] switching from send command CRC to receive command ACK
2022-12-11 15:17:02.583 [bus notice] >310c07040032
2022-12-11 15:17:02.583 [bus debug] notify request: ERR: SYN received
2022-12-11 15:17:02.583 [bus info] scan 0d cmd: 310d070400
2022-12-11 15:17:02.583 [bus debug] ERR: SYN received during receive command ACK, switching to ready
2022-12-11 15:17:02.583 [bus debug] start request 31
2022-12-11 15:17:02.583 [bus debug] arbitration start with 31
2022-12-11 15:17:02.633 [bus debug] arbitration won
2022-12-11 15:17:02.633 [bus debug] arbitration delay 476 micros
2022-12-11 15:17:02.633 [bus debug] switching from ready to send command
2022-12-11 15:17:02.640 [bus debug] send/receive symbol latency 5 ms
2022-12-11 15:17:02.647 [bus debug] send/receive symbol latency 5 ms
2022-12-11 15:17:02.654 [bus debug] send/receive symbol latency 5 ms
2022-12-11 15:17:02.661 [bus debug] send/receive symbol latency 6 ms
2022-12-11 15:17:02.661 [bus debug] switching from send command to send command CRC
2022-12-11 15:17:02.668 [bus debug] notify request: ERR: wrong symbol received
2022-12-11 15:17:02.668 [bus info] scan 0e cmd: 310e070400
2022-12-11 15:17:02.668 [bus debug] ERR: wrong symbol received during send command CRC, switching to skip
2022-12-11 15:17:02.669 [bus debug] start request 31
2022-12-11 15:17:02.669 [bus debug] arbitration start with 31
2022-12-11 15:17:02.713 [bus notice] >310d0704006c<4cfd
2022-12-11 15:17:02.718 [bus debug] arbitration won
2022-12-11 15:17:02.718 [bus debug] arbitration delay 400 micros
2022-12-11 15:17:02.718 [bus info] arbitration delay 400 - 627 micros
2022-12-11 15:17:02.718 [bus debug] switching from ready to send command
2022-12-11 15:17:02.725 [bus debug] send/receive symbol latency 5 ms
2022-12-11 15:17:02.732 [bus debug] send/receive symbol latency 5 ms
2022-12-11 15:17:02.739 [bus debug] send/receive symbol latency 6 ms
2022-12-11 15:17:02.747 [bus debug] send/receive symbol latency 5 ms
2022-12-11 15:17:02.747 [bus debug] switching from send command to send command CRC
2022-12-11 15:17:02.754 [bus debug] notify request: ERR: wrong symbol received
2022-12-11 15:17:02.754 [bus info] scan 12 cmd: 3112070400
2022-12-11 15:17:02.754 [bus debug] ERR: wrong symbol received during send command CRC, switching to skip
2022-12-11 15:17:02.755 [bus debug] start request 31
2022-12-11 15:17:02.755 [bus debug] arbitration start with 31
2022-12-11 15:17:02.800 [bus notice] >310e0704008e<0ef5
2022-12-11 15:17:02.805 [bus debug] arbitration won
2022-12-11 15:17:02.805 [bus debug] arbitration delay 406 micros
2022-12-11 15:17:02.805 [bus debug] switching from ready to send command
2022-12-11 15:17:02.812 [bus debug] send/receive symbol latency 5 ms
2022-12-11 15:17:02.820 [bus debug] send/receive symbol latency 6 ms
2022-12-11 15:17:02.827 [bus debug] send/receive symbol latency 5 ms
2022-12-11 15:17:02.834 [bus debug] send/receive symbol latency 5 ms
2022-12-11 15:17:02.834 [bus debug] switching from send command to send command CRC
2022-12-11 15:17:02.841 [bus debug] notify request: ERR: wrong symbol received
2022-12-11 15:17:02.841 [bus info] scan 14 cmd: 3114070400
2022-12-11 15:17:02.841 [bus debug] ERR: wrong symbol received during send command CRC, switching to skip

**Comment by john30** [comment] 2022-12-18 08:26
duplicate of #717

**Closed as completed by john30** 2022-12-18 08:26 UTC
Labels: duplicate, invalid, hw:foreign:usb
