### ISSUE TITLE
Date / Time change does not work in 22.1

### ISSUE THREAD

**Issue by salvq** [john30/ebusd#548] opened 2022-02-25 19:27 UTC
### Description

Update of date and time does not work in v22.1. It work with the same settings in v21.2

The change of date and time has been issued via mqtt topic in both cases but works only in 21.2
```
pi@rpi4-tv:~ $ sudo mosquitto_pub -h 192.168.1.106 -m '20:11:35' -t 'ebusd/f47/Time/set'
pi@rpi4-tv:~ $ sudo mosquitto_pub -h 192.168.1.106 -m '25.02.2022' -t 'ebusd/f47/Date/set'
```

### Actual behavior

2022-02-25 20:11:35.871 ebusd/f47/Date/set 25.02.2022
2022-02-25 20:11:35.909 ebusd/f47/Time/set 20:11:35

### Expected behavior

2022-02-25 20:08:23.873 ebusd/f47/Date/set 25.02.2022
2022-02-25 20:08:23.911 ebusd/f47/Time/set 20:08:23
2022-02-25 20:08:24.210 ebusd/f47/Date {
2022-02-25 20:08:24.225      "date": {"value": "25.02.2022"}}
2022-02-25 20:08:24.240 ebusd/f47/Time {
2022-02-25 20:08:24.255      "time": {"value": "20:08:23"}}

### ebusd version

latest release

### ebusd arguments

    command: -f --scanconfig --configpath=/ebusd/ebusd-2.1.x/en -d enh:192.168.6.98:9999 -l /var/log/ebusd.log --logareas=all --loglevel=info --httpport=8080 --accesslevel=* --mqtthost=192.168.1.106 --mqttport=1883 --mqttuser=xzy --mqttpass=xzy --mqttjson --mqtttopic=ebusd/%circuit/%name

### Operating system

other

### CPU architecture

x64

### Dockerized

latest

### Hardware interface

adapter 3 Ethernet

### Related integration

MQTT generic

### Logs

v22.1
2022-02-25 20:11:35.871 ebusd/f47/Date/set 25.02.2022
2022-02-25 20:11:35.909 ebusd/f47/Time/set 20:11:35

v21.2
2022-02-25 20:08:23.873 ebusd/f47/Date/set 25.02.2022
2022-02-25 20:08:23.911 ebusd/f47/Time/set 20:08:23
2022-02-25 20:08:24.210 ebusd/f47/Date {
2022-02-25 20:08:24.225      "date": {"value": "25.02.2022"}}
2022-02-25 20:08:24.240 ebusd/f47/Time {
2022-02-25 20:08:24.255      "time": {"value": "20:08:23"}}

**Comment by john30** [comment] 2022-02-26 13:08
duplicate of #523

**Closed as completed by john30** 2022-02-26 13:08 UTC
Labels: duplicate
